			<link rel="stylesheet" href="{{asset('css/linearicons.css')}}">
			<link rel="stylesheet" href="{{asset('home/css/font-awesome.min.css')}}">
			<link rel="stylesheet" href="{{asset('home/css/bootstrap.css')}}">
			<link rel="stylesheet" href="{{asset('home/css/magnific-popup.css')}}">
			<link rel="stylesheet" href="{{asset('home/css/nice-select.css')}}">							
			<link rel="stylesheet" href="{{asset('home/css/animate.min.css')}}">
			<link rel="stylesheet" href="{{asset('home/css/owl.carousel.css')}}">			
			<link rel="stylesheet" href="{{asset('home/css/jquery-ui.css')}}">			
			<link rel="stylesheet" href="{{asset('home/css/main.css')}}">